name: 备份
on:
  #schedule:
   # - cron: "* * * * *"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: Ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: 备份开始...
      run: |
        #rm -rf ./* 
        #git clone https://github.com/okyyds/yydspure.git
        rm -rf /home/runner/work/javascript/javascript/*
        #cp -rf yydspure/* ./
        #rm -rf yydspure
    - name: '提交更新'
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -am 'update'
    - name: Push Dust
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        branch: main
   
    - name: Upload firmware for release
      uses: softprops/action-gh-release@v1
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        files: "./zqkd_read.js"
        name: "test"
        tag_name: "test11"
        body: "ufjdjd"


    - name: 清理旧的发布
      uses: dev-drprasad/delete-older-releases@v0.1.0
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.PAT }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 1
